SET SERVEROUTPUT ON;
/
DECLARE
    V_TEXT VARCHAR2(50) NOT NULL DEFAULT 'HELLO';
BEGIN
    DBMS_OUTPUT.PUT_LINE(V_TEXT);
END;
/
DECLARE
    V_TEXT VARCHAR2(50) NOT NULL DEFAULT 'HELLO';
BEGIN
    V_TEXT := 'PL/SQL';
    DBMS_OUTPUT.PUT_LINE(V_TEXT);
END;
/
DECLARE
    V_TEXT VARCHAR2(50) NOT NULL DEFAULT 'HELLO';
BEGIN
    --V_TEXT := 'PL/SQL' || ' COURSE';
    DBMS_OUTPUT.PUT_LINE(V_TEXT || ' BEGINNER TO ADVANCED');
END;

/
DECLARE
    V_NUMBER NUMBER NOT NULL := 50;
BEGIN
    --V_TEXT := 'PL/SQL' || ' COURSE';
    DBMS_OUTPUT.PUT_LINE(V_NUMBER || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_NUMBER NUMBER(4,2) NOT NULL := 50.22; --LA PRESISION DEBE SER IGUAL O MAYOR AL TOTAL DE LOS NUMEROS
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_NUMBER || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_NUMBER NUMBER(10,1) NOT NULL := 50.22; --LA PRESISION DEBE SER IGUAL O MAYOR AL TOTAL DE LOS NUMEROS
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_NUMBER || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_NUMBER PLS_INTEGER NOT NULL := 59; --SOLO ACEPTA NUMEROS ENTEROS
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_NUMBER || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_NUMBER BINARY_INTEGER NOT NULL := 59; --SOLO ACEPTA NUMEROS ENTEROS
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_NUMBER || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_NUMBER BINARY_FLOAT NOT NULL := 50.22f; --NO SE PUEDE ASIGNAR LA PRESICION, ADEMAS HAY QUE AGREGAR LA 'f' AL FINAL DEL NUMERO
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_NUMBER || ' BEGINNER TO ADVANCED');
END;

/
DECLARE
    V_DATE DATE NOT NULL := SYSDATE; 
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_DATE || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_DATE DATE NOT NULL := '15/05/2023'; 
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_DATE || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_DATE TIMESTAMP NOT NULL := SYSTIMESTAMP; 
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_DATE || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_DATE TIMESTAMP(3) WITH TIME ZONE NOT NULL := SYSTIMESTAMP; 
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_DATE || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_DATE INTERVAL DAY(4) TO SECOND(2) := '24 02:05:21.012'; 
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_DATE || ' BEGINNER TO ADVANCED');
END;
/
DECLARE
    V_DATE INTERVAL YEAR(3) TO MONTH := '122-03'; 
BEGIN    
    DBMS_OUTPUT.PUT_LINE(V_DATE || ' BEGINNER TO ADVANCED');
END;

/
DECLARE
    V_BOOL BOOLEAN := TRUE; 
BEGIN    
    DBMS_OUTPUT.PUT_LINE(sys.diutil.bool_to_int(V_BOOL));
END;