--VARIABLES

--Scalar Data Types
CHAR();
VARCHAR2();
NUMBER(PRECISION,SALE); --3,2 -->999,99
BINARY_INTEGER = PLSINTEGER;
BINARY_FLOAT;
BINARY_DOUBLE;
BOOLEAN;
DATE;
TIMESTAMP(PRECISION); --(P)
TIMESTAMP(P) WHIT TIME ZONE;
TIMESTAMP(P) WHIT LOCAL TIME ZONE;
INTERVAL(P) YEAR TO MONTH;
INTERVAL(P) DAY TO SECOND;

--Variable Naming Rules

--Declaring & initializing & using Variables
	--General usage
	NAME[CONSTANT] DATATYPE [NOT NULL] [:= DEFAULT VALUE | EXPRESSION];

	--USING %TYPE ATTRIBUTE
	[NAME] [TABLE.COLUMN]%TYPE;
	
	--DELIMITADORES & COMMENTING YOUR CODE
	+	SUMNA				<>	DIFERENTE
	-	RESTA				!=	DIFERENTE
	*	MULTIPLICACION		||	CONCATENAR
	/	DIVISION			:=	IGUALAR VALOR
	=	IGUAL				--	COMENTARIO LINEA
	@						/**/	COMENTARIO BLOQUE
	;	TERMINACION
	
	--PL SQL Variable Scope
	BEGIN <<OUTER>>
		DECLARE
		BEGIN 
		  DECLARE
		  BEGIN
		  END;
		END;
	END OUTER;
	
	