SET SERVEROUTPUT ON;
/
DECLARE
    V_OUTER VARCHAR2(50) := 'OUTER';
BEGIN
    BEGIN
        DBMS_OUTPUT.PUT_LINE('INSIDE -> ' || V_OUTER);
    END;
    DBMS_OUTPUT.PUT_LINE(V_OUTER);
END;
/
DECLARE
    V_OUTER VARCHAR2(50) := 'OUTER';
BEGIN
    DECLARE
        V_INNER VARCHAR2(30) := 'INNER VARIABLE';
    BEGIN
        DBMS_OUTPUT.PUT_LINE('INSIDE -> ' || V_OUTER);
        DBMS_OUTPUT.PUT_LINE('INSIDE-INNER -> ' || V_INNER);
    END;
    DBMS_OUTPUT.PUT_LINE(V_OUTER);
END;
/
DECLARE
    V_OUTER VARCHAR2(50) := 'OUTER';
BEGIN
    DECLARE
        V_INNER VARCHAR2(30) := 'INNER VARIABLE';
    BEGIN
        DBMS_OUTPUT.PUT_LINE('INSIDE -> ' || V_OUTER);
        DBMS_OUTPUT.PUT_LINE('INSIDE-INNER -> ' || V_INNER);
    END;
    DBMS_OUTPUT.PUT_LINE('INSIDE-INNER -> ' || V_INNER); --GENERA ERROE POR QUE LA VARIABLE ES INTERNA.
    DBMS_OUTPUT.PUT_LINE(V_OUTER);
END;
/
DECLARE
    V_TEXT VARCHAR2(50) := 'OUT-TEXT!';
BEGIN
    DECLARE
        V_TEXT VARCHAR2(50) := 'IN-TEXT!';
    BEGIN        
        DBMS_OUTPUT.PUT_LINE('INSIDE-INNER -> ' || V_TEXT);
        DBMS_OUTPUT.PUT_LINE('INSIDE-OUTER -> ' || V_TEXT);
    END;
    DBMS_OUTPUT.PUT_LINE('OUTSIDE -> ' || V_TEXT);
END;
/
BEGIN <<OUTER>>
    DECLARE
        V_TEXT VARCHAR2(50) := 'OUT-TEXT!';
    BEGIN
        DECLARE
            V_TEXT VARCHAR2(50) := 'IN-TEXT!';
        BEGIN        
            DBMS_OUTPUT.PUT_LINE('INSIDE-INNER -> ' || V_TEXT);
            DBMS_OUTPUT.PUT_LINE('INSIDE-OUTER -> ' || OUTER.V_TEXT);
        END;
        DBMS_OUTPUT.PUT_LINE('OUTSIDE -> ' || V_TEXT);
    END;
END OUTER;