SET SERVEROUTPUT ON;
SET AUTOPRINT ON;
/
VARIABLE VAR_TEXT VARCHAR2(30);
VARIABLE VAR_NUMBER NUMBER;
VARIABLE VAR_DATE DATE;
/
DECLARE
    V_TEXT VARCHAR2(30);
BEGIN
    :VAR_TEXT := 'Hello SQL';
    :VAR_NUMBER := 20;
    V_TEXT := :VAR_TEXT;
--dbms_output.put_line(v_text);
--dbms_output.put_line(:var_text);
END;
/
PRINT VAR_TEXT;

/
VARIABLE VAR_SQL NUMBER;
/
BEGIN 
  :VAR_SQL := 100;
END;
/
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = :VAR_SQL;