--CONTROL STRUCTURES

	--IF STATEMENT
	IF [CONDITION] THEN [STATEMENTS];
	
	IF [CONDITION] THEN
		[STATEMENTS]
	ELSIF [CONDITION] THEN
		[STATEMENTS]
	ELSIF [CONDITION] THEN
		[STATEMENTS]
	ELSE
		[STATEMENTS]
	END IF;
	
	--CASE EXPRESSIONS
	CASE [EXPRESSION || CONDITION]
		WHEN [CONDITION1]  THEN [RESULT1]
		WHEN [CONDITION2]  THEN [RESULT2]
		WHEN [CONDITION_N] THEN [RESULT_N]
		ELSE [RESULT_N]
	END;
	
	--LOOPS
		--BASIC LOOPS
		LOOP
			[LOGICA]
			EXIT[WHEN CONDITION];
		END LOOP;
	
		--WHILE LOOPS
		WHILE [CONDITION] LOOP
			[LOGICA]
		END LOOP;
		
		--FOR LOOPS
		FOR [CONTADOR] IN [REVERSE] [VALOR_INICIAL]..[VALOR_FINAL] LOOP
			[LOGICA]
		END LOOP;
	
	--NESTING AND LABELING THE LOOPS
	
	--CONTINUE STATEMENT
		CONTINUE [LABEL_NAME] WHEN [CONDITION]
	
	--GOTO STATEMENT
		GOTO [LABEL_NAME]
		
		